name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-node@v3
      - uses: actions/cache@v3
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('package.json') }}
      - run: |
          echo '${{ secrets.DATA }}' > categories.json
          npm i
          npm run build
          npx staticrypt dist/index.html ${{ secrets.PASS }}
          rm -rf .staticrypt.json
          mv dist/index_encrypted.html dist/index.html
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
